< config.mk

##Annotate variant effect in the INFO column. Output is VCF format
##A summary stats will be generated, as indicated by the --stats_file flag
results/%.vep.$DESCRIPTION.vcf: results/%.vep.$DESCRIPTION.tsv
	set -x
	mkdir -p `dirname $target`
	mkdir -p QC
	$VEP -i data/$stem.vcf.gz -o $target.build \
		--stats_file QC/$stem"_stats.txt" \
		--stats_text \
		--cache --offline \
		--dir $VEPconfig --assembly $GENOME_VERSION \
		--species "homo_sapiens" \
		--af --af_1kg \
		--gene_phenotype \
		--canonical --check_existing \
		--pick \
		--vcf_info_field ANN \
		--numbers --regulatory \
		--biotype \
		--vcf \
		--buffer_size 10000 \
	&& mv $target.build $target


##Annotate variant effect in the INFO column. Output is TSV format
##A summary stats will be generated, as indicated by the --stats_file flag
results/%.vep.$DESCRIPTION.tsv: data/%.vcf.gz
	set -x
	mkdir -p `dirname $target`
	mkdir QC
	$VEP -i $prereq -o $target.build \
		-custom $ANNOTATION_DB,$DESCRIPTION,bed,overlap,0 \
		--stats_file QC/$stem"_stats.html" \
		--cache --offline \
		--dir $VEPconfig --assembly $GENOME_VERSION \
		--species "homo_sapiens" \
		--af --af_1kg \
		--gene_phenotype \
		--canonical --check_existing --exclude_null_alleles \
		--pick \
		--numbers --regulatory \
		--biotype \
		--tab \
		--buffer_size 10000 \
	&& mv $target.build $target

