MKSHELL=/bin/bash

## DESCRIPTION
##
## mk module to convert Fantom enhancer database *.bed to a reformatted bed file

## USAGE:
## Alternative 1: Single target execution.
##      `mk <SPECIFIC_TARGET>`; where SPECIFIC_TARGET is any line printed by the `/bin/create-targets` script in this module
##
## Alternative 2: Multiple target tandem execution.
##      `bin/targets | xrags mk`
##
## Alternative 3: Multiple target parallel execution. NOTE: requires HTCondor with the right configuration
##      `condor submit'
##  AUTHOR:
##      Eugenia Zarza (eugenia.zarza@gmail.com), for Winter Genomics (http://www.wintergenomics.com/) - 2018

## Load configurations from file
## Config file contains paths to xhmm executables


# Index bed file
# ============================================
#
results/%.bed.gz.tbi: results/%.bed.gz
	set -x
	mkdir -p $(dirname $target)
	echo "Indexing bed..."
	echo $target
	echo $prereq
	tabix \
		-h -p bed results/$stem.bed.gz
#
#Compress bed file
# ============================================
#
results/%.bed.gz: results/%.bed
	set -x
	mkdir -p $(dirname $target)
	echo "Compressing bed..."
	echo $target
	echo $prereq
	bgzip -c \
		results/$stem.bed > results/$stem.bed.gz.build \
	&&mv results/$stem.bed.gz.build results/$stem.bed.gz
#	
#Create bed file from EnhancerDisease text file
# ============================================
#
results/%.bed: data/%.bed
	set -x
        mkdir -p $(dirname $target)
        echo "Creating bed..."
        echo $target
        echo $prereq
	database_name=$(basename $prereq)
	#create header
	echo "#track name=\"Enhancer_Fantom\" description=\"bed edited from file obtained from" $database_name "(http://slidebase.binf.ku.dk/). Columns are:chromosome, start, end, enhancerID\"" > $target.build
	#extract columns of interest and add database delimiter, sort according to chromosome and coordinates, append to file with header
	awk 'BEGIN {FS="\t"}; {print $1"\t"$2"\t"$3"\t""enhancer_"$4"[Fantom_enhancer]"}' $prereq  | \
	sort -k1,1 -k2,2n -k3,3n -t$'\t' >> $target.build \
	&&mv $target.build $target
